### ISSUE TITLE
Encrypted Localization files to a readable text!

### ISSUE THREAD

**Issue by 4Brad-23** [theawesomecoder61/Blacksmith#3]
"Assassin's Creed Odyssey/DataPC.forge/LocalizationPackage_English_Subtitles" - Please, the tool only extract these files in ".dat/.acod" types?!

**Comment by 4Brad-23** [comment]
Hey, man is there a solution to this, are you working on one?  - Update me, man!

**Comment by 4Brad-23** [comment]
Hey, man is there a solution to this, are you working on one?  - Update me, man!

**Comment by theawesomecoder61** [comment]
Not interested in localization, sorry.
