### ISSUE TITLE
Immortals Fenyx Rising

### ISSUE THREAD

**Issue by meerminman** [theawesomecoder61/Blacksmith#5]
Is it possible you can add support for Immortals Fenyx Rising?

**Comment by TSelman61** [comment]
I cannot help you with this.  But I'm sure my friend who works on this subject can give you information about it.
Did you mention this on the Discord server?
https://discord.gg/tjyCvcP
[https://cdn.discordapp.com/icons/563766610226053120/8ac48af185afacd6b2c412d04d17d6be.jpg?size=256]<https://discord.gg/tjyCvcP>
Join the Blacksmith Discord Server!<https://discord.gg/tjyCvcP>
Check out the Blacksmith community on Discord - hang out with 613 other members and enjoy free voice and text chat.
discord.gg


________________________________
Gönderen: meerminman <notifications@github.com>
Gönderildi: 25 Şubat 2021 Perşembe 08:08
Kime: theawesomecoder61/Blacksmith <Blacksmith@noreply.github.com>
Bilgi: Subscribed <subscribed@noreply.github.com>
Konu: [theawesomecoder61/Blacksmith] Immortals Fenyx Rising (#5)


Is it possible you can add support for Immortals Fenyx Rising?

**Comment by meerminman** [comment]
Thank you for the reply, I did not know that there was a discord server. I will check the discord server then.

**Comment by theawesomecoder61** [comment]
Yes, Fenyx Rising support will come.
